Add new module for datadog events
ZeroGachis/.github pull request #48
Opened 2023-12-29 15:47 UTC by rodo

This will allow us to create event when we deploy

2023-12-29 16:09 UTC, nicolasbriere1 requested changes

2023-12-29 16:09 UTC, nicolasbriere1 commented on .github/workflows/datadog-events.yml
> +          api-key: ${{ secrets.DD_API_KEY }}
Tu peux pas gérer le multi env Datadog avec ce système. La gestion des secrets on essaie de le limiter au maximum côté Github. Le mieux c'est de récupérer les clés qu'on stock dans chaque compte AWS .

```
      - name: Get tiers Tools credentials
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
              DD_API_KEY,datadog/${{ inputs.AWS_ACCOUNT_ID || vars.AWS_ACCOUNT_ID || vars.PULL_REQUEST_AWS_ACCOUNT_ID }}/technical-account/api-key
              DD_APP_KEY,datadog/${{ inputs.AWS_ACCOUNT_ID || vars.AWS_ACCOUNT_ID || vars.PULL_REQUEST_AWS_ACCOUNT_ID }}/technical-account/app-key
```

2023-12-29 16:09 UTC, nicolasbriere1 commented on .github/workflows/datadog-events.yml
> +      application-name:
Est ce qu'on ne mettrait pas une valeur par défault égale au nom du repo Github ? Ca permettrait de limiter la complexité d'appel côté service.

2023-12-29 16:09 UTC, nicolasbriere1 commented on .github/workflows/datadog-events.yml
> +                - "application:${{ application-name }}"
Côté Datadog, on utilise le tag `service` pas `application`. Ca me parait plus cohérent de rester dans le fonctionnement actuel sur ces labels.

2023-12-29 16:09 UTC, nicolasbriere1 commented on .github/workflows/datadog-events.yml
> +        type: string
On pourrait rajouter un attribut de version ? Actuellement ca serait le `release_tag` mais ca pourrait devenir un véritable numéro plus tard.

2024-01-04 09:48 UTC, Qlebrun commented
Wouldn't that be redundant with the already setup [ECS deployment events](https://smartway-prod.datadoghq.com/event/explorer?cols=&messageDisplay=expanded-lg&options=&refresh_mode=sliding&sort=DESC&view=spans&from_ts=1704360595444&to_ts=1704361495444&live=true) ?

2024-03-27 09:18 UTC, nicolasbriere1 commented
Tu veux en faire quoi de cette PR @rodo ?

2024-03-27 09:38 UTC, rodo commented
On a convenu je crois que cela n'était pas nécessaire alors je la clos.

2024-03-27 09:38 UTC, closed without merging